env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://localhost:8080
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://localhost:8080
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: FAIL
    customMessage: ''
    id: 10015
  - action: FAIL
    customMessage: ''
    id: 10020
  - action: FAIL
    customMessage: ''
    id: 10021
  - action: FAIL
    customMessage: ''
    id: 10035
  - action: FAIL
    customMessage: ''
    id: 10038
  - action: FAIL
    customMessage: ''
    id: 40012
  - action: FAIL
    customMessage: ''
    id: 40018
  - action: WARN
    customMessage: ''
    id: 90022
  - action: IGNORE
    customMessage: ''
    id: 10096
  type: outputSummary
